### PR TITLE
Enable OP-TEE on 4.9

### PR DESCRIPTION
**Pull request by vchong**

### CODE REVIEW

**Comment by shawnguo2** [comment]
@vchong I'm wondering what those *** not for mainline *** commits are, and why they need to necessarily be on the branch.

**Comment by shawnguo2** [comment]
@vchong Can you please rebase the branch to 4.9 kernel as of today?  I'm asking because instead of dummy ION driver, we are using a HiSilicon specific ION driver on Poplar.

**Comment by vchong** [comment]
@shawnguo2 Ok, I'll rebase but if SWG ION patches cannot be applied on top of HiSi ION driver, i.e. not compatible, then we cannot use OP-TEE SDP feature, which is something LHG needs.

**Comment by vchong** [comment]
> I'm wondering what those *** not for mainline *** commits are, and why they need to necessarily be on the branch.

Those are just to mark SWG kernel patches that have not been submitted/accepted/merged upstream yet, but needed by Linaro groups for extended features.

**Comment by vchong** [comment]
@shawnguo2 Rebase was ok. I've repushed the changes. Thanks!

**Comment by shawnguo2** [comment]
> I'll rebase but if SWG ION patches cannot be applied on top of HiSi ION driver, i.e. not compatible, then we cannot use OP-TEE SDP feature, which is something LHG needs.

I do not completely understand how special the OP-TEE SDP memory is.  But I guess we should have only one single ION driver on Poplar platform.  That said, the secure memory used by OP-TEE SDP feature should coming from HiSi ION driver as well.  Per my understanding, the changes you are integrating into dummy driver should probably be made into HiSi ION driver instead.  I'm wondering how this was done on Hikey which should have its own ION driver too.

**Comment by vchong** [comment]
@shawnguo2 I've removed the OP-TEE ION driver. Please test again. Thanks!

**Comment by shawnguo2** [comment]
> I've removed the OP-TEE ION driver. Please test again. Thanks!

The warnings are gone, and I can run optee tests now, but got the following segmentation faults.

root@linaro-developer:~# tee-supplicant &
[1] 2410
root@linaro-developer:~# xtest 
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# regression
#
######################################################
 
* regression_1001 Core self tests
ERROR:   [0x0] TEE-CORE:tee_entry_std:543: Bad arg address 0x67011000
/home/r65073/dis[   63.470970] xtest[2411]: unhandled level 2 translation fault (11) at 0x00000000, esr 0x92000006
k/aspen/optee/op[   63.481066] pgd = ffff80006edd6000
tee_test/host/xt[   63.485848] [00000000] *pgd=000000006ef62003est/regression_1, *pud=00000000670a1003000.c:285: res h, *pmd=0000000000000000as an unexpected
 value: 0xffff00[   63.499635] 
0e = TEEC_ERROR_[   63.502517] CPU: 3 PID: 2411 Comm: xtest Not tainted 4.9.51-03837-ga124b825c8d5 #84
COMMUNICATION, e[   63.511552] Hardware name: HiSilicon Poplar Development Board (DT)
xpected 0x0 = TE[   63.519098] task: ffff800067171900 task.stack: ffff8000759e8000
EC_SUCCESS
[   63.526392] PC is at 0xffffa35114e4
[   63.530903] LR is at 0xffffa35114c0
[   63.534393] pc : [<0000ffffa35114e4>] lr : [<0000ffffa35114c0>] pstate: 60000000
[   63.541793] sp : 0000ffffe55cb720
[   63.545110] x29: 0000ffffe55cb720 x28: 0000000000000000 
[   63.550427] x27: 0000000000000000 x26: 0000000000000000 
[   63.555744] x25: 0000000000000000 x24: 0000000000000000 
[   63.561067] x23: 0000000000000000 x22: 0000000000000000 
[   63.566385] x21: 0000000000402550 x20: 0000000000000000 
[   63.571703] x19: 000000000042e918 x18: 0000000000000000 
[   63.577027] x17: 0000ffffa33674c0 x16: 0000ffffa35222b0 
[   63.582344] x15: 0000000000000018 x14: 0000000000000000 
[   63.587660] x13: 0000000000000000 x12: 0000000000000000 
[   63.592983] x11: 0000000000000020 x10: 0101010101010101 
[   63.598300] x9 : 706f2f656574706f x8 : 0000000000000040 
[   63.603617] x7 : 000000000000000c x6 : 4355535f43454554 
[   63.608947] x5 : 0000000000000000 x4 : 0000ffffe55cb8c0 
[   63.614275] x3 : 0000ffffe55cb890 x2 : fffffffffffffff0 
[   63.619595] x1 : 0000000000000000 x0 : 0000000000000000 
[   63.624917] 
Segmentation fault

**Comment by shawnguo2** [comment]
@vchong There are quite some debug messages in phase of U-Boot and kernel booting, which should probably be cleaned up before merging?

DEBUG:   [0x0] TEE-CORE:add_phys_mem:531: CFG_TA_RAM_START type TA_RAM 0x01200000 size 0x00e00000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:531: VCORE_UNPG_RW_PA type TEE_RAM_RW 0x01040000 size 0x001c0000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:531: VCORE_UNPG_RX_PA type TEE_RAM_RX 0x01000000 size 0x00040000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:531: CONSOLE_UART_BASE type IO_NSEC 0xf8a00000 size 0x00200000
DEBUG:   [0x0] TEE-CORE:verify_special_mem_areas:475: SDP memory [c00000 1000000]
DEBUG:   [0x0] TEE-CORE:verify_special_mem_areas:475: NSEC DDR memory [2080000 40000000]
DEBUG:   [0x0] TEE-CORE:add_va_space:570: type RES_VASPACE size 0x01400000
DEBUG:   [0x0] TEE-CORE:add_va_space:570: type SHM_VASPACE size 0x02000000
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:703: type TEE_RAM_RX   va 0x01000000..0x0103ffff pa 0x01000000..0x0103ffff size 0x00040000 (smallpg)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:703: type TEE_RAM_RW   va 0x01040000..0x011fffff pa 0x01040000..0x011fffff size 0x001c0000 (smallpg)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:703: type NSEC_SHM     va 0x01200000..0x015fffff pa 0x00400000..0x007fffff size 0x00400000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:703: type RES_VASPACE  va 0x01600000..0x029fffff pa 0x00000000..0x013fffff size 0x01400000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:703: type SHM_VASPACE  va 0x02a00000..0x049fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:703: type TA_RAM       va 0x04a00000..0x057fffff pa 0x01200000..0x01ffffff size 0x00e00000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:703: type IO_NSEC      va 0x05800000..0x059fffff pa 0xf8a00000..0xf8bfffff size 0x00200000 (pgdir)
DEBUG:   [0x0] TEE-CORE:init_xlation_table:411: xlat used: 1/5
DEBUG:   [0x0] TEE-CORE:init_xlation_table:411: xlat used: 2/5
...

INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:3204513537
INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:237
INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:3204513539
INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:247
INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:2986344457
INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:91
INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:2986344455
INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:40
INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:2986344459
INFO:    TEE-CORE: core/arch/arm/tee/entry_fast.c:147

**Comment by vchong** [comment]
@shawnguo2

> The warnings are gone, and I can run optee tests now, but got the following segmentation faults.

I've also tried again with the ION patches removed, but cannot reproduce the error. optee test passed without issues. Please note that I ran optee test with below log level changes as well, but don't think those would cause any kind of segfault.

> There are quite some debug messages in phase of U-Boot and kernel booting, which should probably be cleaned up before merging?

I've changed https://github.com/Linaro/poplar-tools/pull/16 to build optee_os with INFO instead of DEBUG log level so you shouldn't see these anymore.

```
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:3204513537
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:237
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:3204513539
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:247
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:2986344457
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:91
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:2986344455
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:40
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:171: args->a0:2986344459
INFO: TEE-CORE: core/arch/arm/tee/entry_fast.c:147
```

These are just extra 'debug' prints from my optee_os `poplar3` branch (not the `poplar_for_hisi_review` branch though). They wouldn't go upstream. In any case, I've removed them from the `poplar3` branch as well.

**Comment by shawnguo2** [comment]
I just tried a SDP enabled build from all your latest branch, and saw all debug messages gone, but still got the same segment fault.  Can you paste your tee-pager.bin for me to try?

**Comment by vchong** [comment]
Can you check a few things please?

1. Can you paste the boot log?

2. What is the output of `dmesg | grep tee`?

3. No errors when running `tee-supplicant`?

4. Did you apply https://github.com/Linaro/poplar-u-boot/pull/2 before building u-boot and fip.bin?

**Comment by vchong** [comment]
Also, are you using my arm-tf fork?

**Comment by shawnguo2** [comment]
> Can you paste the boot log?

[optee_boot.log](https://github.com/Linaro/poplar-linux/files/1516908/optee_boot.log)

> What is the output of dmesg | grep tee?

[    2.465863] optee: probing for conduit method from DT.
[    2.475744] optee: initialized driver

> No errors when running tee-supplicant?

No errors.

> Did you apply Linaro/poplar-u-boot#2 before building u-boot and fip.bin?

Yes, I did.

> Also, are you using my arm-tf fork?

Yes, I'm using that.

**Comment by vchong** [comment]
@shawnguo2 and I worked out that the segfault was due to optee_os not mapping addresses higher than 1gb. This has been fixed in optee_os but closing this anyway and replace with https://github.com/Linaro/poplar-linux/pull/3 which includes ION/SDP support.

**Pull request closed without merging**
